# Generated by Django 4.2.11 on 2024-08-16 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateOfCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.date(2024, 8, 16))),
                ('state_of_charge', models.FloatField()),
            ],
        ),
    ]
