# Generated by Django 4.2.11 on 2024-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateofcharge',
            name='current_status',
            field=models.CharField(default='idle', max_length=50),
        ),
        migrations.AddField(
            model_name='stateofcharge',
            name='invertor_power',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stateofcharge',
            name='state_of_charge',
            field=models.FloatField(default=0),
        ),
    ]
