# Generated by Django 4.2.11 on 2024-08-19 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0002_stateofcharge_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateofcharge',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2024, 8, 19)),
        ),
    ]
