# Generated by Django 4.2.11 on 2024-08-19 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0003_alter_stateofcharge_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateofcharge',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 11, 34, 17, 235016, tzinfo=datetime.timezone.utc)),
        ),
    ]
