# Generated by Django 4.2.11 on 2024-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0005_alter_stateofcharge_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateofcharge',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
