# Generated by Django 4.2.11 on 2024-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0006_alter_stateofcharge_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('state_of_charge', models.FloatField(default=0)),
                ('flow_last_min', models.FloatField(default=0)),
                ('invertor_power', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='StateOfCharge',
        ),
    ]
