# Generated by Django 4.2.11 on 2024-08-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0007_batterylivestatus_delete_stateofcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterylivestatus',
            name='devId',
            field=models.CharField(default='batt-0001', max_length=20),
        ),
    ]
